# Generated by Django 4.2.6 on 2024-01-28 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_page_followings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_join_group', models.DateTimeField(default=django.utils.timezone.now)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_member_information', to='page.page')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_join_group', models.DateTimeField(default=django.utils.timezone.now)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='page_members',
            field=models.ManyToManyField(related_name='group_page_members', to='group.pagemember'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='group.member'),
        ),
    ]
