# Generated by Django 4.2.6 on 2024-01-28 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_pagemember_member_group_page_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pagemember',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
