# Generated by Django 4.2.6 on 2024-01-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_remove_group_avatar_alter_group_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='show_group',
            field=models.BooleanField(default=False),
        ),
    ]
