# Generated by Django 4.2.6 on 2024-02-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_joingrouprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='anonymous_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='anyone_can_join',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='anyone_can_poll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='anyone_can_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='ban_list',
            field=models.ManyToManyField(related_name='ban_list', to='group.member'),
        ),
        migrations.AddField(
            model_name='group',
            name='pending_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
