# Generated by Django 4.2.6 on 2024-02-06 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_group_moderators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='group.question')),
            ],
        ),
        migrations.AddField(
            model_name='joingrouprequest',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='group.answer'),
        ),
    ]
