# Generated by Django 4.2.6 on 2023-10-24 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_post_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposted_by_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
