# Generated by Django 4.2.6 on 2023-11-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_rename_reposted_by_users_post_reported_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='only_me',
            field=models.BooleanField(default=False),
        ),
    ]
