# Generated by Django 4.2.6 on 2023-11-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_remove_comment_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
