# Generated by Django 4.2.6 on 2023-11-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='tags'),
        ),
    ]
