# Generated by Django 4.2.6 on 2023-11-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_comment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_avatar_post',
            field=models.BooleanField(default=False),
        ),
    ]
