# Generated by Django 4.2.6 on 2024-01-17 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0002_page_likes_page_likes_count'),
        ('post', '0019_pagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to='page.page'),
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_avatar_post', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending', models.BooleanField(default=True)),
                ('attachments', models.ManyToManyField(blank=True, to='post.postattachment')),
                ('comments', models.ManyToManyField(blank=True, to='post.comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_posts', to='page.page')),
                ('likes', models.ManyToManyField(blank=True, to='post.like')),
                ('reported_by_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
