# Generated by Django 4.2.6 on 2024-01-20 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0004_page_is_page'),
        ('post', '0020_alter_pagepost_created_by_grouppost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PagePostAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='post_attachments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_post_attachments', to='page.page')),
            ],
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='post.pagepostattachment'),
        ),
    ]
