# Generated by Django 4.2.6 on 2024-01-23 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_page_phone_number'),
        ('post', '0021_alter_grouppost_created_by_pagepostattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_likes', to='page.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, editable=False, null=True, verbose_name='tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to='page.page')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
