# Generated by Django 4.2.6 on 2024-01-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_pagelike_pagecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepost',
            name='page_comments',
            field=models.ManyToManyField(blank=True, to='post.pagecomment'),
        ),
        migrations.AddField(
            model_name='pagepost',
            name='page_likes',
            field=models.ManyToManyField(blank=True, to='post.pagelike'),
        ),
    ]
