# Generated by Django 4.2.6 on 2024-01-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_member_last_access_pagemember_last_access'),
        ('post', '0023_pagepost_page_comments_pagepost_page_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_own', to='group.group'),
        ),
    ]
