# Generated by Django 4.2.6 on 2024-02-03 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_group_moderators'),
        ('post', '0024_grouppost_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='is_avatar_post',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='reported_by_users',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='reported_by_members',
            field=models.ManyToManyField(blank=True, to='group.member'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to='group.member'),
        ),
        migrations.CreateModel(
            name='MemberPostAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='post_attachments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_post_attachments', to='group.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_likes', to='group.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, editable=False, null=True, verbose_name='tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_comments', to='group.member')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='post.memberpostattachment'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='comments',
            field=models.ManyToManyField(blank=True, to='post.membercomment'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='likes',
            field=models.ManyToManyField(blank=True, to='post.memberlike'),
        ),
    ]
