# Generated by Django 4.2.6 on 2024-02-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_remove_grouppost_is_avatar_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
