# Generated by Django 4.2.6 on 2024-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_remove_group_questions_remove_group_rules_and_more'),
        ('post', '0027_polloption_grouppostpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppostpoll',
            name='allow_add_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grouppostpoll',
            name='multiple_options',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='polloption',
            name='vote_by',
            field=models.ManyToManyField(related_name='vote_by', to='group.member'),
        ),
    ]
