# Generated by Django 4.2.6 on 2024-02-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_grouppostpoll_allow_add_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppostpoll',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
