# Generated by Django 4.2.6 on 2024-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_alter_grouppostpoll_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='votes_count',
            field=models.IntegerField(default=0),
        ),
    ]
