# Generated by Django 4.2.6 on 2023-10-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new_friend_request', 'New friendrequest'), ('accepted_friend_request', 'Accepted friendrequest'), ('rejected_friend_request', 'Rejected friendrequest'), ('post_like', 'Post like'), ('post_comment', 'Post comment')], max_length=50),
        ),
    ]
