# Generated by Django 4.2.6 on 2024-01-23 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_page_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0021_alter_grouppost_created_by_pagepostattachment_and_more'),
        ('notification', '0007_alter_notification_type_of_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_by_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_created_notifications', to='page.page'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationForPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('type_of_notification', models.CharField(choices=[('post_like', 'Post like'), ('post_comment', 'Post comment'), ('tag_comment', 'Tag comment'), ('react_story', 'React story'), ('like_page', 'Like page')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_notifications_for_page', to=settings.AUTH_USER_MODEL)),
                ('created_by_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_created_notifications_for_page', to='page.page')),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_received_notifications', to='page.page')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
