# Generated by Django 4.2.6 on 2023-10-30 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='seen',
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
