# Generated by Django 4.2.6 on 2023-10-30 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_conversation_seen_conversationmessage_seen_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='see_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_message', to='chat.seenuser'),
        ),
    ]
