# Generated by Django 4.2.6 on 2023-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_seenuser_alter_conversationmessage_seen_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_message', to='chat.seenuser'),
        ),
    ]
