# Generated by Django 4.2.6 on 2023-10-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversationmessage_is_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='is_last_message',
        ),
    ]
