# Generated by Django 4.2.6 on 2023-10-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_conversationmessage_is_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='is_latest_message',
            field=models.BooleanField(default=False),
        ),
    ]
