# Generated by Django 4.2.6 on 2023-11-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_messageattachment_conversationmessage_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
