# Generated by Django 4.2.6 on 2023-11-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_conversationmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='theme',
            field=models.CharField(blank=True, default='Cổ điển', max_length=50),
        ),
    ]
