# Generated by Django 4.2.6 on 2023-11-25 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_conversation_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(blank=True, default='Cổ điển', max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groupchat', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='moderators_groupchat', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='group_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
