# Generated by Django 4.2.6 on 2023-11-25 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_groupconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupconversation',
            name='moderators',
            field=models.ManyToManyField(null=True, related_name='moderators_groupchat', to=settings.AUTH_USER_MODEL),
        ),
    ]
