# Generated by Django 4.2.6 on 2023-11-26 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_alter_groupconversation_moderators'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest_message', models.BooleanField(default=False)),
                ('attachments', models.ManyToManyField(blank=True, to='chat.messageattachment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sent_messages', to=settings.AUTH_USER_MODEL)),
                ('group_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='chat.groupconversation')),
                ('seen_by', models.ManyToManyField(related_name='group_seen_message', to='chat.seenuser')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_received_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
