# Generated by Django 4.2.6 on 2023-11-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_groupconversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconversation',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
