# Generated by Django 4.2.6 on 2023-11-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_groupconversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconversation',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_avatars'),
        ),
    ]
