# Generated by Django 4.2.6 on 2023-11-29 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0015_polloption_grouppoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='users_vote',
            field=models.ManyToManyField(null=True, related_name='users_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
