# Generated by Django 4.2.6 on 2023-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_polloption_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='poll_option_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
