# Generated by Django 4.2.6 on 2023-11-29 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_polloption_poll_option_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
