# Generated by Django 4.2.6 on 2023-11-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_polloption_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppoll',
            name='group_conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_poll', to='chat.groupconversation'),
        ),
    ]
