# Generated by Django 4.2.6 on 2023-11-30 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_grouppoll_group_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_notifications', to='chat.groupconversation')),
            ],
        ),
    ]
