# Generated by Django 4.2.6 on 2023-12-01 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0022_alter_groupnotification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='users_vote',
            field=models.ManyToManyField(related_name='users_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
