# Generated by Django 4.2.6 on 2024-01-24 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_page_followings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0023_alter_polloption_users_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(blank=True, default='Cổ điển', max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_in_conversations', to='page.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeenPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_page', to='page.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='message_attachments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_message_attachments', to='page.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest_message', models.BooleanField(default=False)),
                ('attachments', models.ManyToManyField(blank=True, to='chat.messageattachment')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_messages', to='chat.pageconversation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_messages', to=settings.AUTH_USER_MODEL)),
                ('created_by_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sent_messages', to='page.page')),
                ('page_attachments', models.ManyToManyField(blank=True, to='chat.pagemessageattachment')),
                ('seen_by', models.ManyToManyField(related_name='user_seen_message', to='chat.seenuser')),
                ('seen_by_page', models.ManyToManyField(related_name='page_seen_message', to='chat.seenpage')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_received_messages', to=settings.AUTH_USER_MODEL)),
                ('sent_to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_received_messages', to='page.page')),
            ],
        ),
    ]
