# Generated by Django 4.2.6 on 2024-01-26 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_page_followings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0024_pageconversation_seenpage_pagemessageattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageconversationmessage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pageconversationmessage',
            name='created_by_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_sent_messages', to='page.page'),
        ),
        migrations.AlterField(
            model_name='pageconversationmessage',
            name='sent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pageconversationmessage',
            name='sent_to_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_received_messages', to='page.page'),
        ),
    ]
