# Generated by Django 4.2.6 on 2024-01-17 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images')),
                ('biography', models.CharField(blank=True, default='', max_length=255)),
                ('followers_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('page_type', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_admin', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='page_followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='page_following', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='page_moderators', to=settings.AUTH_USER_MODEL)),
                ('whos_active', models.ManyToManyField(related_name='active_moderators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
