# Generated by Django 4.2.6 on 2024-01-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_likes_page_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='business_hours_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='close_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='biography',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
