# Generated by Django 4.2.6 on 2024-01-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_page_business_hours_status_page_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_page',
            field=models.BooleanField(default=True),
        ),
    ]
