# Generated by Django 4.2.6 on 2024-01-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_is_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='phone_number',
        ),
    ]
