# Generated by Django 4.2.6 on 2024-01-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_page_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='other_page_followers',
            field=models.ManyToManyField(to='page.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='other_page_following',
            field=models.ManyToManyField(to='page.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='other_page_likes',
            field=models.ManyToManyField(to='page.page'),
        ),
    ]
