# Generated by Django 4.2.6 on 2024-01-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_page_other_page_followers_page_other_page_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='followings_count',
            field=models.IntegerField(default=0),
        ),
    ]
