# Generated by Django 4.2.6 on 2023-12-12 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0003_mediastory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_react', models.CharField(choices=[('like', 'Like story'), ('heart', 'Heart story'), ('love', 'Love story'), ('laugh', 'Laugh story'), ('suprise', 'Suprise story'), ('sad', 'Sad story'), ('angry', 'Angry story')], max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_react_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mediastory',
            name='react_by',
            field=models.ManyToManyField(related_name='react_media_story', to='story.reactstory'),
        ),
        migrations.AddField(
            model_name='textstory',
            name='react_by',
            field=models.ManyToManyField(related_name='react_text_story', to='story.reactstory'),
        ),
    ]
