# Generated by Django 4.2.6 on 2023-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_reactstory_mediastory_react_by_textstory_react_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactstory',
            name='type_of_react',
            field=models.CharField(choices=[('like', 'Like react'), ('heart', 'Heart react'), ('love', 'Love react'), ('laugh', 'Laugh react'), ('suprise', 'Suprise react'), ('sad', 'Sad react'), ('angry', 'Angry react')], max_length=50),
        ),
    ]
