# Generated by Django 4.2.6 on 2023-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_remove_mediastory_react_by_remove_textstory_react_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediastory',
            name='reacted_by',
            field=models.ManyToManyField(related_name='react_media_story', to='story.reactstory'),
        ),
    ]
