# Generated by Django 4.2.6 on 2023-12-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_mediastory_reacted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyattachment',
            name='zoom_image',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
