# Generated by Django 4.2.6 on 2023-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_storyattachment_zoom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyattachment',
            name='rotate',
            field=models.CharField(default='0deg', max_length=50),
        ),
    ]
