# Generated by Django 4.2.6 on 2023-12-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_storyattachment_rotate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyattachment',
            name='rotate',
            field=models.CharField(default='rotate-0', max_length=50),
        ),
    ]
