# Generated by Django 4.2.6 on 2024-01-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0018_alter_reactstory_type_of_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyattachment',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='story_attachments_image'),
        ),
        migrations.AlterField(
            model_name='storyattachment',
            name='video',
            field=models.FileField(default='', null=True, upload_to='story_attachments_video'),
        ),
    ]
