# Generated by Django 4.2.6 on 2024-03-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_groupsearchkeyword_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsearchkeyword',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='searchkeyword',
            options={'ordering': ('-created_at',)},
        ),
    ]
