# Generated by Django 4.2.6 on 2023-10-09 04:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('606546e3-b932-42db-9990-2b03afa9b2cb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
