# Generated by Django 4.2.6 on 2023-10-10 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ec98f98-6037-4487-9d88-e9169ddf988a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
