# Generated by Django 4.2.6 on 2023-10-10 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a0bd9108-c8a8-48fd-803a-2db403644f9a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
