# Generated by Django 4.2.6 on 2023-10-21 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_people_you_may_know'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='people_you_may_know',
        ),
        migrations.AddField(
            model_name='user',
            name='people_you_may_know',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
