# Generated by Django 4.2.6 on 2023-11-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
