# Generated by Django 4.2.6 on 2023-11-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_relationship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='partner',
        ),
    ]
