# Generated by Django 4.2.6 on 2023-11-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_user_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
