# Generated by Django 4.2.6 on 2023-11-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_user_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
