# Generated by Django 4.2.6 on 2023-11-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_relationshiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiprequest',
            name='relationship_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
