# Generated by Django 4.2.6 on 2023-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_relationshiprequest_relationship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshiprequest',
            name='relationship_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
