# Generated by Django 4.2.6 on 2023-11-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_relationshiprequest_relationship_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('year', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('only_me', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('only_me', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('only_me', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='living_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.ManyToManyField(related_name='birthday', to='account.birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='phone_numbers', to='account.phonenumber'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.ManyToManyField(related_name='websites', to='account.website'),
        ),
    ]
