# Generated by Django 4.2.6 on 2023-11-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_birthday_phonenumber_website_user_biography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_numbers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
