# Generated by Django 4.2.6 on 2023-11-19 10:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_user_birthday_remove_user_phone_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
