# Generated by Django 4.2.6 on 2023-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='user + <django.db.models.fields.UUIDField>', max_length=255),
        ),
    ]
