# Generated by Django 4.2.6 on 2023-11-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.ManyToManyField(related_name='birthday', to='account.birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='lived_cities',
            field=models.ManyToManyField(related_name='lived_cities', to='account.livedcity'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='phone_numbers', to='account.phonenumber'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.ManyToManyField(related_name='websites', to='account.website'),
        ),
    ]
