# Generated by Django 4.2.6 on 2023-11-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_user_biography_user_birthday_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedcity',
            name='year_end',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='livedcity',
            name='year_start',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
