# Generated by Django 4.2.6 on 2023-11-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_livedcity_year_end_alter_livedcity_year_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedcity',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livedcity',
            name='year_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
