# Generated by Django 4.2.6 on 2023-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_livedcity_year_end_alter_livedcity_year_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedcity',
            name='year_end',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='livedcity',
            name='year_start',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
