# Generated by Django 4.2.6 on 2023-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_livedcity_year_end_alter_livedcity_year_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lived_cities',
        ),
    ]
