# Generated by Django 4.2.6 on 2023-11-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_remove_user_lived_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LivedCity',
        ),
    ]
